[package]
name = "themelio-stf"
version = "0.7.0"
authors = ["Themelio Labs"]
edition = "2021"

description = "Core state-transition function and data structures for Themelio"
license = "MPL-2.0"
repository = "https://github.com/themeliolabs/themelio-stf"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.arbitrary]
version = "1.0.2"
features = ["derive"]

[dependencies.genawaiter]
version = "0.99.1"
default-features = false
features = []

[dependencies.imbl]
version = "1.0.1"
features = ["serde"]

[dependencies.serde]
version = "1.0.126"
features = ["derive"]

[dependencies]
catvec = "0.1.5"
dashmap = "4.0.2"
defmac = "0.2.1"
derive_more = "0.99.16"
ethnum = "1.0.3"
hex = "0.4.3"
log = "0.4.14"
num = "0.4.0"
num_enum = "0.5.4"
novasmt = "0.1.9"
once_cell = "1.8.0"
ordered-float = "2.8.0"
parking_lot = "0.11.2"
rayon = "1.5.1"
rustc-hash = "1.1.0"
scopeguard = "1.1.0"
serde_repr = "0.1.7"
smallvec = "1.7.0"
stdcode = "0.1.3"
tap = "1.0.1"
thiserror = "1.0.28"
tmelcrypt = "0.2.1"

[target.'cfg(fuzzing)'.dependencies]
honggfuzz = "0.5.54"
env_logger = "0.9.0"
jemallocator ="0.3.2"

[dev-dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dev-dependencies]
lazy_static = "1.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
logos = "0.12.0"
rand = "0.8.4"
criterion ="0.3"
quanta ="0.9"


[[bench]]
name = "bench"
harness = false