[package]
name = "themelio-stf"
version = "0.4.2"
authors = ["Themelio Labs"]
edition = "2018"

description = "Core state-transition function and data structures for Themelio"
license = "MPL-2.0"
repository = "https://github.com/themeliolabs/themelio-stf"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tmelcrypt="0.1"
stdcode="0.1.1"
# cached={version="0.23.0", default-features=false, features=["proc_macro"]}
num_enum = "0.5.1"
hex= "0.4.3"
thiserror= "1.0.25"
rayon= "1.5.1"
im = { version = "15.0.0", features = ["serde"] }
arbitrary={ version = "1", features = ["derive"] }
ethnum= "1.0.3"
derive_more="0.99"
dashmap={ version = "4.0.2" }
parking_lot= "0.11.1"
log= "0.4.14"
defmac = "0.2.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_repr = "0.1.7"
once_cell= "1.7.2"
genawaiter= {version = "0.99.1", default-features=false, features=[]}
num= "0.3.1"
novasmt= "0.1.6"
smallvec = "1.6.1"
tap="1"
rustc-hash = "1.1.0"
stacker="0.1"

[target.'cfg(fuzzing)'.dependencies] 
honggfuzz="0.5"
env_logger="0.8"

[dev-dependencies]
rstest = "0.6.4"
lazy_static = "1.4.0"
beaver = "0.1.0"
chrono = { version = "0.4.19", features = ["serde"] }
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
logos= "0.11.4"
rand= "0.7.3"
criterion="0.3"


[[bench]]
name = "bench"
harness = false
